source 'https://github.com/CocoaPods/Specs.git'

target 'EdgeAnimateView-iOS_Example', :exclusive => true do
  pod "EdgeAnimateView-iOS", :path => "../"

  pod 'POViewFrameBuilder'
  pod 'AOTToolkit/UI'
end

target 'EdgeAnimateView-iOS_Tests', :exclusive => true do
  pod "EdgeAnimateView-iOS", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
